### PR TITLE
Param type validation for Hash

### PR DESCRIPTION
**Pull request by felixibel**
Hola @richdrich 
I thought this might be useful in case when users send arrays, etc, where we actually expect a hash.

### CODE REVIEW

**Comment by richdrich** [comment]
Looks ok to me I think

**Comment by kylorhall** [comment]
@felixibel This is a bit old.

**Comment by felixibel** [comment]
Yes, and I cannot even remember what for it was needed. Apparently for nothing, everything is working.

Will we need it 'now', or shall we just close it (without a merge)?

**Comment by kylorhall** [comment]
Not quite sure the use-case for hash params, but it's simple enough.

I merged master in so it would get a Travis build.  If it passes, let's just merge it.  Not harmful at all as it's simple, with tests.

**Comment by kylorhall** [comment]
@felixibel Another ping on this I guess, running through stale PRs.

I would actually just suggest closing this as we use a fair bit of hash-like objects lately and I'm not 100% sure if they're actually hashes or hash-like objects.

Alternatively, would need QA with Investapp to merge this, which I'm also fine with, but needs some follow-through.

**Comment by felixibel** [comment]
Lets close it. I don't need it. No one needs it.

**Pull request closed without merging**
